'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const path=require('node:path');
const root=path.resolve(__dirname,'..');const sandbox={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'assets/data.js'),'utf8'),sandbox);const data=sandbox.window.JEV_ATLAS;
test('video catalogue has unique real cases and valid categories',()=>{assert.ok(data.cases.length>=20);assert.equal(new Set(data.cases.map(x=>x.id)).size,data.cases.length);const cats=new Set(data.categories.map(x=>x.id));for(const c of data.cases){assert.ok(cats.has(c.category));assert.match(c.id,/^[a-z0-9-]+$/);assert.ok(c.title&&c.summary&&c.author&&c.note);assert.ok(c.metrics.length>=1&&c.metrics.length<=3);}});
test('every card has a published video, not an illustration or hypothetical example',()=>{for(const c of data.cases){assert.ok(['mp4','x'].includes(c.media.type));assert.ok(['published-video-thumbnail','publisher-video-file'].includes(c.media.evidence));assert.equal(new URL(c.source).protocol,'https:');if(c.media.type==='x'){assert.match(c.media.id,/^\d{15,22}$/);assert.ok(c.source.endsWith(c.media.id));assert.match(c.media.poster,/^https:\/\/pbs\.twimg\.com\/(amplify_video_thumb|ext_tw_video_thumb)\//);}else{assert.equal(new URL(c.media.url).hostname,'raw.githubusercontent.com');assert.ok(new URL(c.media.url).pathname.endsWith('.mp4'));}}});
test('dedicated media is unique; a single demo is not padded into many cards',()=>{const keys=data.cases.map(c=>{const match=(c.media.url+' '+c.media.poster).match(/(?:amplify_video(?:_thumb)?|ext_tw_video(?:_thumb)?)\/(\d+)/);return match?match[1]:(c.media.url||c.media.id);});assert.equal(new Set(keys).size,keys.length);assert.equal(new Set(data.cases.map(c=>c.source)).size,data.cases.length);});
test('figures have labels and review records',()=>{for(const c of data.cases){for(const m of c.metrics){assert.ok(m.value&&m.label);}assert.match(c.reviewed,/^\d{4}-\d{2}-\d{2}$/);assert.equal(new URL(c.research).protocol,'https:');}});
test('entry points are local and the initial page does not load social widgets',()=>{const html=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const id of ['categories','cards','search','inline-player','saved-toggle','empty'])assert.ok(html.includes(`id="${id}"`));assert.ok(!html.includes('widgets.js'));assert.ok(!html.includes('iframe'));assert.ok(!/120\s*개|120\+/.test(html));assert.match(html,/<html lang="ko">/);for(const f of ['assets/data.js','assets/app.js','assets/styles.css','assets/favicon.svg'])assert.ok(fs.existsSync(path.join(root,f)));});
test('narrow grids and reduced motion are supported',()=>{const css=fs.readFileSync(path.join(root,'assets/styles.css'),'utf8');assert.ok(css.includes('grid-template-columns:repeat(2,minmax(0,1fr))'));assert.ok(css.includes('grid-template-columns:1fr'));assert.ok(css.includes('prefers-reduced-motion'));assert.ok(css.includes('[hidden]'));});
test('safe embeds, local bookmarks, source fallback and stale callback guard exist',()=>{const js=fs.readFileSync(path.join(root,'assets/app.js'),'utf8');for(const s of ['playerEpoch','createTweet','noopener noreferrer','failedPlayer','localStorage','aria-pressed','validIds','textContent'])assert.ok(js.includes(s));assert.ok(!js.includes('eval('));});

test('every Jevable addition uses its original post in the official X player',()=>{const added=data.cases.filter(c=>new URL(c.research).hostname==='jevable.com');assert.equal(added.length,50);for(const c of added){assert.equal(c.media.type,'x');assert.equal(c.source.split('/').pop(),c.media.id);assert.equal(c.media.url,undefined);}});
